spring:
  application:
    name: flagforge-control-api
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  info:
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: false

